import {
  Ambulance,
  ArrowsClockwise,
  ArrowLeft,
  Barcode,
  CalendarBlank,
  Car,
  ChatCircleText,
  ClipboardText,
  ClockCounterClockwise,
  Crosshair,
  CreditCard,
  Database,
  Drop,
  EnvelopeSimple,
  Eye,
  FunnelX,
  Gauge,
  Hash,
  House,
  IdentificationCard,
  List,
  MapPin,
  MapPinLine,
  MapTrifold,
  MagnifyingGlass,
  Moon,
  PencilSimple,
  Phone,
  SignOut,
  Sun,
  ArrowsDownUp,
  ArrowUp,
  ArrowDown,
  Trash,
  UsersThree,
  Warning,
  CheckCircle,
  Lock,
  LockOpen,
  Wrench,
  X,
} from '@phosphor-icons/react';

const ICONS = {
  dashboard: House,
  vehicles: Ambulance,
  map: MapTrifold,
  mapLocate: MapPinLine,
  users: UsersThree,
  legacy: ClockCounterClockwise,
  menu: List,
  logout: SignOut,
  themeLight: Sun,
  themeDark: Moon,
  db: Database,
  resetFilters: FunnelX,
  resetMapView: Crosshair,
  sync: ArrowsClockwise,
  car: Car,
  detail: Eye,
  edit: PencilSimple,
  sort: ArrowsDownUp,
  sortAsc: ArrowUp,
  sortDesc: ArrowDown,
  warning: Warning,
  approve: CheckCircle,
  lock: Lock,
  unlock: LockOpen,
  delete: Trash,
  email: EnvelopeSimple,
  phone: Phone,
  service: Wrench,
  serviceRecords: ClipboardText,
  ccsCard: CreditCard,
  search: MagnifyingGlass,
  close: X,
  arrowLeft: ArrowLeft,
  chatCircleText: ChatCircleText,
  drop: Drop,
  mapPin: MapPin,
  calendarBlank: CalendarBlank,
  gauge: Gauge,
  identifier: IdentificationCard,
  barcode: Barcode,
  clockCounterClockwise: ClockCounterClockwise,
  pencilSimple: PencilSimple,
};

export default function AppIcon({ name, size = 18, weight = 'regular', className = '', ...rest }) {
  const Icon = ICONS[name] || Car;
  return <Icon className={`app-icon ${className}`.trim()} size={size} weight={weight} aria-hidden="true" {...rest} />;
}
