import {
  Ambulance,
  ArrowsClockwise,
  Crosshair,
  Car,
  ClockCounterClockwise,
  Database,
  Eye,
  FunnelX,
  House,
  List,
  MapTrifold,
  Moon,
  PencilSimple,
  SignOut,
  Sun,
  ArrowsDownUp,
  ArrowUp,
  ArrowDown,
  Warning,
  UsersThree,
  CheckCircle,
  Lock,
  LockOpen,
  Trash,
  EnvelopeSimple,
  Phone,
} from '@phosphor-icons/react';

const ICONS = {
  dashboard: House,
  vehicles: Ambulance,
  map: MapTrifold,
  users: UsersThree,
  legacy: ClockCounterClockwise,
  menu: List,
  logout: SignOut,
  themeLight: Sun,
  themeDark: Moon,
  db: Database,
  resetFilters: FunnelX,
  resetMapView: Crosshair,
  sync: ArrowsClockwise,
  car: Car,
  detail: Eye,
  edit: PencilSimple,
  sort: ArrowsDownUp,
  sortAsc: ArrowUp,
  sortDesc: ArrowDown,
  warning: Warning,
  approve: CheckCircle,
  lock: Lock,
  unlock: LockOpen,
  delete: Trash,
  email: EnvelopeSimple,
  phone: Phone,
};

export default function AppIcon({ name, size = 18, weight = 'regular', className = '', ...rest }) {
  const Icon = ICONS[name] || Car;
  return <Icon className={`app-icon ${className}`.trim()} size={size} weight={weight} aria-hidden="true" {...rest} />;
}
